export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const LOG_IN = 'LOG_IN';
export const REGISTRATION_USER = 'REGISTRATION_USER';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOG_AUT = 'LOG_AUT';


export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const PUT_CATEGORY = 'PUT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const GET_PRODUCTS = 'GET_GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const PUT_PRODUCT = 'PUT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
