export const GET_USER_BY_ID = 'GET_USER_BY_ID';
// export const SUCCESS_GET_USER_BY_ID = 'SUCCESS_GET_USER_BY_ID';
// export const FAIL_GET_USER_BY_ID = 'FAIL_GET_USER_BY_ID';


export const LOG_IN = 'LOG_IN';
// export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
// export const FAIL_LOGIN = 'FAIL_LOGIN';

export const REGISTRATION_USER = 'REGISTRATION_USER';
// export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS';
// export const REGISTRATION_USER_FAIL = 'REGISTRATION_USER_FAIL';

export const LOG_AUT = 'LOG_AUT';
// export const SUCCESS_LOGIN_AUT = 'SUCCESS_LOGIN_AUT';
// export const FAIL_LOGIN_AUT = 'FAIL_LOGIN_AUT';


export const CREATE_NEW_USER = 'CREATE_NEW_USER';
// export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
// export const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';

export const CREATE_NEW_RATE = 'CREATE_NEW_RATE';
// export const CREATE_NEW_RATE_SUCCESS = 'CREATE_NEW_RATE_SUCCESS';
// export const CREATE_NEW_RATE_FAIL = 'CREATE_NEW_RATE_FAIL';

export const GET_RATES = 'GET_RATES';
// export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
// export const GET_RATES_FAIL = 'GET_RATES_FAIL';

export const GET_RATE_BY_ID = 'GET_RATE_BY_ID';
// export const GET_RATE_BY_ID_SUCCESS = 'GET_RATE_BY_ID_SUCCESS';
// export const GET_RATE_BY_ID_FAIL = 'GET_RATE_BY_ID_FAIL';

export const PUT_RATE = 'PUT_RATE';
// export const PUT_RATE_SUCCESS = 'PUT_RATE_SUCCESS';
// export const PUT_RATE_FAIL = 'PUT_RATE_FAIL';

export const GET_COMMON_RATES = 'GET_COMMON_RATES';
// export const GET_COMMON_RATES_SUCCESS = 'GET_COMMON_RATES_SUCCESS';
// export const GET_COMMON_RATES_FAIL = 'GET_COMMON_RATES_FAIL';
